// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260305230449_deleteRoleClaimEnterpriseId")]
    partial class deleteRoleClaimEnterpriseId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.EmissionSources.EmissionSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("uuid")
                        .HasColumnName("installation_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("InstallationId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_emission_source_installation_id_code");

                    b.ToTable("emission_source", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.EmissionSources.Pollutant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_pollutant");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_pollutant_code");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_pollutant_name");

                    b.ToTable("pollutant", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Enterprises.EmissionLimit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EmissionSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("emission_source_id");

                    b.Property<int>("Period")
                        .HasColumnType("integer")
                        .HasColumnName("period");

                    b.Property<Guid>("PermitId")
                        .HasColumnType("uuid")
                        .HasColumnName("permit_id");

                    b.Property<Guid>("PollutantId")
                        .HasColumnType("uuid")
                        .HasColumnName("pollutant_id");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_emission_limit");

                    b.HasIndex("EmissionSourceId")
                        .HasDatabaseName("ix_emission_limit_emission_source_id");

                    b.HasIndex("PermitId")
                        .HasDatabaseName("ix_emission_limit_permit_id");

                    b.HasIndex("PollutantId")
                        .HasDatabaseName("ix_emission_limit_pollutant_id");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_emission_limit_unit_id");

                    b.ToTable("emission_limit", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Enterprises.Enterprise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Edrpou")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("edrpou");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("RiskGroup")
                        .HasColumnType("integer")
                        .HasColumnName("risk_group");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sector_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_enterprise");

                    b.HasIndex("Edrpou")
                        .IsUnique()
                        .HasDatabaseName("ix_enterprise_edrpou");

                    b.HasIndex("SectorId")
                        .HasDatabaseName("ix_enterprise_sector_id");

                    b.ToTable("enterprise", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Enterprises.IedCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_ied_category");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_ied_category_code");

                    b.ToTable("ied_category", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Enterprises.Installation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("IedCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("ied_category_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_installation");

                    b.HasIndex("IedCategoryId")
                        .HasDatabaseName("ix_installation_ied_category_id");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_installation_site_id");

                    b.ToTable("installation", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Enterprises.Permit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("authority");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("uuid")
                        .HasColumnName("installation_id");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("number");

                    b.Property<int>("PermitStatus")
                        .HasColumnType("integer")
                        .HasColumnName("permit_status");

                    b.Property<int>("PermitType")
                        .HasColumnType("integer")
                        .HasColumnName("permit_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.HasKey("Id")
                        .HasName("pk_permit");

                    b.HasIndex("InstallationId")
                        .HasDatabaseName("ix_permit_installation_id");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_permit_number");

                    b.ToTable("permit", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Enterprises.Sector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_sector");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_sector_code");

                    b.ToTable("sector", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Enterprises.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("EnterpriseId")
                        .HasColumnType("uuid")
                        .HasColumnName("enterprise_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int?>("SanitaryZoneRadius")
                        .HasColumnType("integer")
                        .HasColumnName("sanitary_zone_radius");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_site");

                    b.HasIndex("EnterpriseId")
                        .HasDatabaseName("ix_site_enterprise_id");

                    b.ToTable("site", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Monitoring.ExceedanceEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DetectedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("LimitId")
                        .HasColumnType("uuid")
                        .HasColumnName("limit_id");

                    b.Property<decimal>("Magnitude")
                        .HasColumnType("numeric")
                        .HasColumnName("magnitude");

                    b.Property<Guid>("MeasurementId")
                        .HasColumnType("uuid")
                        .HasColumnName("measurement_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_exceedance_event");

                    b.HasIndex("LimitId")
                        .HasDatabaseName("ix_exceedance_event_limit_id");

                    b.HasIndex("MeasurementId")
                        .HasDatabaseName("ix_exceedance_event_measurement_id");

                    b.ToTable("exceedance_event", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Monitoring.MeasureUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<int>("Dimension")
                        .HasColumnType("integer")
                        .HasColumnName("dimension");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("symbol");

                    b.Property<decimal>("ToBaseFactor")
                        .HasColumnType("numeric")
                        .HasColumnName("to_base_factor");

                    b.HasKey("Id")
                        .HasName("pk_measure_unit");

                    b.HasIndex("Symbol")
                        .IsUnique()
                        .HasDatabaseName("ix_measure_unit_symbol");

                    b.ToTable("measure_unit", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Monitoring.Measurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<Guid>("EmissionSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("emission_source_id");

                    b.Property<int>("Period")
                        .HasColumnType("integer")
                        .HasColumnName("period");

                    b.Property<Guid>("PollutantId")
                        .HasColumnType("uuid")
                        .HasColumnName("pollutant_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_measurement");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_measurement_device_id");

                    b.HasIndex("PollutantId")
                        .HasDatabaseName("ix_measurement_pollutant_id");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_measurement_unit_id");

                    b.HasIndex("EmissionSourceId", "PollutantId", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("ix_measurement_emission_source_id_pollutant_id_timestamp");

                    b.ToTable("measurement", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Monitoring.MonitoringDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid?>("EmissionSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("emission_source_id");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("uuid")
                        .HasColumnName("installation_id");

                    b.Property<DateTime?>("InstalledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("installed_at");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean")
                        .HasColumnName("is_online");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serial_number");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_monitoring_device");

                    b.HasIndex("EmissionSourceId")
                        .HasDatabaseName("ix_monitoring_device_emission_source_id");

                    b.HasIndex("InstallationId")
                        .HasDatabaseName("ix_monitoring_device_installation_id");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_monitoring_device_serial_number");

                    b.ToTable("monitoring_device", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Monitoring.MonitoringPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("uuid")
                        .HasColumnName("installation_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_monitoring_plan");

                    b.HasIndex("InstallationId")
                        .HasDatabaseName("ix_monitoring_plan_installation_id");

                    b.ToTable("monitoring_plan", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Monitoring.MonitoringRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EmissionSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("emission_source_id");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer")
                        .HasColumnName("frequency");

                    b.Property<Guid>("MonitoringPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("monitoring_plan_id");

                    b.Property<Guid>("PollutantId")
                        .HasColumnType("uuid")
                        .HasColumnName("pollutant_id");

                    b.HasKey("Id")
                        .HasName("pk_monitoring_requirement");

                    b.HasIndex("EmissionSourceId")
                        .HasDatabaseName("ix_monitoring_requirement_emission_source_id");

                    b.HasIndex("PollutantId")
                        .HasDatabaseName("ix_monitoring_requirement_pollutant_id");

                    b.HasIndex("MonitoringPlanId", "EmissionSourceId", "PollutantId")
                        .IsUnique()
                        .HasDatabaseName("ix_monitoring_requirement_monitoring_plan_id_emission_source_i");

                    b.ToTable("monitoring_requirement", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User.EnterpriseInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid>("EnterpriseId")
                        .HasColumnType("uuid")
                        .HasColumnName("enterprise_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_enterprise_invitation");

                    b.HasIndex("EnterpriseId")
                        .HasDatabaseName("ix_enterprise_invitation_enterprise_id");

                    b.ToTable("enterprise_invitation", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<Guid>("EnterpriseId")
                        .HasColumnType("uuid")
                        .HasColumnName("enterprise_id");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("EnterpriseId")
                        .HasDatabaseName("ix_roles_enterprise_id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", "usr");
                });

            modelBuilder.Entity("Domain.Entities.User.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<DateTime>("CreatedClaim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_claim");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_claims_role_id");

                    b.ToTable("role-claims", "usr");
                });

            modelBuilder.Entity("Domain.Entities.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<Guid>("EnterpriseId")
                        .HasColumnType("uuid")
                        .HasColumnName("enterprise_id");

                    b.Property<string>("FamilyName")
                        .HasColumnType("text")
                        .HasColumnName("family_name");

                    b.Property<string>("GeneratedCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("generated_code");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("EnterpriseId")
                        .HasDatabaseName("ix_users_enterprise_id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", "usr");
                });

            modelBuilder.Entity("Domain.Entities.User.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user-claims", "usr");
                });

            modelBuilder.Entity("Domain.Entities.User.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<DateTime>("LoggedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_on");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user-logins", "usr");
                });

            modelBuilder.Entity("Domain.Entities.User.UserRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_valid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_refresh_tokens");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_refresh_tokens_user_id");

                    b.ToTable("user-refresh-tokens", "usr");
                });

            modelBuilder.Entity("Domain.Entities.User.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("CreatedUserRoleDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_user_role_date");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user-roles", "usr");
                });

            modelBuilder.Entity("Domain.Entities.User.UserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("GeneratedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_time");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user-tokens", "usr");
                });

            modelBuilder.Entity("Domain.Entities.EmissionSources.AirEmissionSource", b =>
                {
                    b.HasBaseType("Domain.Entities.EmissionSources.EmissionSource");

                    b.Property<double>("DesignFlowRate")
                        .HasColumnType("double precision")
                        .HasColumnName("design_flow_rate");

                    b.Property<double>("Diameter")
                        .HasColumnType("double precision")
                        .HasColumnName("diameter");

                    b.Property<double>("Height")
                        .HasColumnType("double precision")
                        .HasColumnName("height");

                    b.ToTable("air_emission_source", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.EmissionSources.WaterEmissionSource", b =>
                {
                    b.HasBaseType("Domain.Entities.EmissionSources.EmissionSource");

                    b.Property<double>("DesignFlowRate")
                        .HasColumnType("double precision")
                        .HasColumnName("design_flow_rate");

                    b.Property<string>("Receiver")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("receiver");

                    b.ToTable("water_emission_source", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.EmissionSources.EmissionSource", b =>
                {
                    b.HasOne("Domain.Entities.Enterprises.Installation", "Installation")
                        .WithMany("EmissionSources")
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_emission_source_installation_installation_id");

                    b.Navigation("Installation");
                });

            modelBuilder.Entity("Domain.Entities.Enterprises.EmissionLimit", b =>
                {
                    b.HasOne("Domain.Entities.EmissionSources.EmissionSource", "EmissionSource")
                        .WithMany("EmissionLimits")
                        .HasForeignKey("EmissionSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_emission_limit_emission_source_emission_source_id");

                    b.HasOne("Domain.Entities.Enterprises.Permit", "Permit")
                        .WithMany("EmissionLimits")
                        .HasForeignKey("PermitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_emission_limit_permit_permit_id");

                    b.HasOne("Domain.Entities.EmissionSources.Pollutant", "Pollutant")
                        .WithMany("EmissionLimits")
                        .HasForeignKey("PollutantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_emission_limit_pollutant_pollutant_id");

                    b.HasOne("Domain.Entities.Monitoring.MeasureUnit", "Unit")
                        .WithMany("EmissionLimits")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_emission_limit_measure_unit_unit_id");

                    b.Navigation("EmissionSource");

                    b.Navigation("Permit");

                    b.Navigation("Pollutant");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Domain.Entities.Enterprises.Enterprise", b =>
                {
                    b.HasOne("Domain.Entities.Enterprises.Sector", "Sector")
                        .WithMany("Enterprises")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_enterprise_sector_sector_id");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Domain.Entities.Enterprises.Installation", b =>
                {
                    b.HasOne("Domain.Entities.Enterprises.IedCategory", "IedCategory")
                        .WithMany("Installations")
                        .HasForeignKey("IedCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_installation_ied_category_ied_category_id");

                    b.HasOne("Domain.Entities.Enterprises.Site", "Site")
                        .WithMany("Installations")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_installation_site_site_id");

                    b.Navigation("IedCategory");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Domain.Entities.Enterprises.Permit", b =>
                {
                    b.HasOne("Domain.Entities.Enterprises.Installation", "Installation")
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_permit_installation_installation_id");

                    b.Navigation("Installation");
                });

            modelBuilder.Entity("Domain.Entities.Enterprises.Site", b =>
                {
                    b.HasOne("Domain.Entities.Enterprises.Enterprise", "Enterprise")
                        .WithMany("Sites")
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_site_enterprise_enterprise_id");

                    b.Navigation("Enterprise");
                });

            modelBuilder.Entity("Domain.Entities.Monitoring.ExceedanceEvent", b =>
                {
                    b.HasOne("Domain.Entities.Enterprises.EmissionLimit", "Limit")
                        .WithMany()
                        .HasForeignKey("LimitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exceedance_event_emission_limit_limit_id");

                    b.HasOne("Domain.Entities.Monitoring.Measurement", "Measurement")
                        .WithMany()
                        .HasForeignKey("MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exceedance_event_measurement_measurement_id");

                    b.Navigation("Limit");

                    b.Navigation("Measurement");
                });

            modelBuilder.Entity("Domain.Entities.Monitoring.Measurement", b =>
                {
                    b.HasOne("Domain.Entities.Monitoring.MonitoringDevice", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_measurement_monitoring_device_device_id");

                    b.HasOne("Domain.Entities.EmissionSources.EmissionSource", "EmissionSource")
                        .WithMany("Measurements")
                        .HasForeignKey("EmissionSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_measurement_emission_source_emission_source_id");

                    b.HasOne("Domain.Entities.EmissionSources.Pollutant", "Pollutant")
                        .WithMany("Measurements")
                        .HasForeignKey("PollutantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_measurement_pollutant_pollutant_id");

                    b.HasOne("Domain.Entities.Monitoring.MeasureUnit", "Unit")
                        .WithMany("Measurements")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_measurement_measure_unit_unit_id");

                    b.Navigation("Device");

                    b.Navigation("EmissionSource");

                    b.Navigation("Pollutant");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Domain.Entities.Monitoring.MonitoringDevice", b =>
                {
                    b.HasOne("Domain.Entities.EmissionSources.EmissionSource", "EmissionSource")
                        .WithMany("MonitoringDevices")
                        .HasForeignKey("EmissionSourceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_monitoring_device_emission_source_emission_source_id");

                    b.HasOne("Domain.Entities.Enterprises.Installation", "Installation")
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_monitoring_device_installation_installation_id");

                    b.Navigation("EmissionSource");

                    b.Navigation("Installation");
                });

            modelBuilder.Entity("Domain.Entities.Monitoring.MonitoringPlan", b =>
                {
                    b.HasOne("Domain.Entities.Enterprises.Installation", "Installation")
                        .WithMany("MonitoringPlans")
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_monitoring_plan_installation_installation_id");

                    b.Navigation("Installation");
                });

            modelBuilder.Entity("Domain.Entities.Monitoring.MonitoringRequirement", b =>
                {
                    b.HasOne("Domain.Entities.EmissionSources.EmissionSource", "EmissionSource")
                        .WithMany("MonitoringRequirements")
                        .HasForeignKey("EmissionSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_monitoring_requirement_emission_source_emission_source_id");

                    b.HasOne("Domain.Entities.Monitoring.MonitoringPlan", "MonitoringPlan")
                        .WithMany("Requirements")
                        .HasForeignKey("MonitoringPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_monitoring_requirement_monitoring_plan_monitoring_plan_id");

                    b.HasOne("Domain.Entities.EmissionSources.Pollutant", "Pollutant")
                        .WithMany("MonitoringRequirements")
                        .HasForeignKey("PollutantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_monitoring_requirement_pollutant_pollutant_id");

                    b.Navigation("EmissionSource");

                    b.Navigation("MonitoringPlan");

                    b.Navigation("Pollutant");
                });

            modelBuilder.Entity("Domain.Entities.User.EnterpriseInvitation", b =>
                {
                    b.HasOne("Domain.Entities.Enterprises.Enterprise", "Enterprise")
                        .WithMany("Invitations")
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enterprise_invitation_enterprise_enterprise_id");

                    b.Navigation("Enterprise");
                });

            modelBuilder.Entity("Domain.Entities.User.Role", b =>
                {
                    b.HasOne("Domain.Entities.Enterprises.Enterprise", "Enterprise")
                        .WithMany()
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roles_enterprise_enterprise_id");

                    b.Navigation("Enterprise");
                });

            modelBuilder.Entity("Domain.Entities.User.RoleClaim", b =>
                {
                    b.HasOne("Domain.Entities.User.Role", "Role")
                        .WithMany("Claims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claims_asp_net_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.User.User", b =>
                {
                    b.HasOne("Domain.Entities.Enterprises.Enterprise", "Enterprise")
                        .WithMany("Users")
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_enterprise_enterprise_id");

                    b.Navigation("Enterprise");
                });

            modelBuilder.Entity("Domain.Entities.User.UserClaim", b =>
                {
                    b.HasOne("Domain.Entities.User.User", "User")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_asp_net_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.User.UserLogin", b =>
                {
                    b.HasOne("Domain.Entities.User.User", "User")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.User.UserRefreshToken", b =>
                {
                    b.HasOne("Domain.Entities.User.User", "User")
                        .WithMany("UserRefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_refresh_tokens_asp_net_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.User.UserRole", b =>
                {
                    b.HasOne("Domain.Entities.User.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("Domain.Entities.User.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.User.UserToken", b =>
                {
                    b.HasOne("Domain.Entities.User.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.EmissionSources.AirEmissionSource", b =>
                {
                    b.HasOne("Domain.Entities.EmissionSources.EmissionSource", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.EmissionSources.AirEmissionSource", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_air_emission_source_emission_source_id");
                });

            modelBuilder.Entity("Domain.Entities.EmissionSources.WaterEmissionSource", b =>
                {
                    b.HasOne("Domain.Entities.EmissionSources.EmissionSource", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.EmissionSources.WaterEmissionSource", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_water_emission_source_emission_source_id");
                });

            modelBuilder.Entity("Domain.Entities.EmissionSources.EmissionSource", b =>
                {
                    b.Navigation("EmissionLimits");

                    b.Navigation("Measurements");

                    b.Navigation("MonitoringDevices");

                    b.Navigation("MonitoringRequirements");
                });

            modelBuilder.Entity("Domain.Entities.EmissionSources.Pollutant", b =>
                {
                    b.Navigation("EmissionLimits");

                    b.Navigation("Measurements");

                    b.Navigation("MonitoringRequirements");
                });

            modelBuilder.Entity("Domain.Entities.Enterprises.Enterprise", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("Sites");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.Enterprises.IedCategory", b =>
                {
                    b.Navigation("Installations");
                });

            modelBuilder.Entity("Domain.Entities.Enterprises.Installation", b =>
                {
                    b.Navigation("EmissionSources");

                    b.Navigation("MonitoringPlans");
                });

            modelBuilder.Entity("Domain.Entities.Enterprises.Permit", b =>
                {
                    b.Navigation("EmissionLimits");
                });

            modelBuilder.Entity("Domain.Entities.Enterprises.Sector", b =>
                {
                    b.Navigation("Enterprises");
                });

            modelBuilder.Entity("Domain.Entities.Enterprises.Site", b =>
                {
                    b.Navigation("Installations");
                });

            modelBuilder.Entity("Domain.Entities.Monitoring.MeasureUnit", b =>
                {
                    b.Navigation("EmissionLimits");

                    b.Navigation("Measurements");
                });

            modelBuilder.Entity("Domain.Entities.Monitoring.MonitoringPlan", b =>
                {
                    b.Navigation("Requirements");
                });

            modelBuilder.Entity("Domain.Entities.User.Role", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.User.User", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Logins");

                    b.Navigation("Tokens");

                    b.Navigation("UserRefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
